<a href="https://qworld.net" target="_blank" align="left"><img src="https://gitlab.com/qworld/qeducation/qbook101/raw/main/qworld/images/header.jpg" align="left"></a>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $

_prepared by Claudia Zendejas-Morales_

<font size="28px" style="font-size:28px;" align="left"><b> <font color="blue"> Solutions for </font>Math with Python </b></font>
<br>
<br><br>

<a name="task1"></a>
<h3> Task 1</h3>

Define the variables `opposite = 8` and `A = 25` (degrees) and find:

- the `hypotenuse` side
- the `adjacent`side
- the angle `B`

<h3>Solution</h3>

In [1]:
from math import sin, cos, pi

opposite = 8
A = 25

A_radians = A * pi / 180

hypotenuse = opposite / sin(A_radians)

adjacent = hypotenuse * cos(A_radians)

B = 180 - 90 - A    # use the fact that all inside angles of a triangle sum up 180°


print("The hypotenuse side is", hypotenuse)
print("The adjacent side is", adjacent)
print("The angle B is", B)

The hypotenuse side is 18.929612665219988
The adjacent side is 17.15605536407647
The angle B is 65


<a name="task2"></a>
<h3> Task 2</h3>

Using a loop, find the result of $i^2,i^3,\cdot,i^{10}$, what can you say about the observed behaviour?

<h3>Solution</h3>

In [2]:
z = complex(0, 1)

for exponent in range(2, 11):
    new_z = z**exponent
    print("i to the power of", exponent, "is", new_z)

i to the power of 2 is (-1+0j)
i to the power of 3 is (-0-1j)
i to the power of 4 is (1+0j)
i to the power of 5 is 1j
i to the power of 6 is (-1+0j)
i to the power of 7 is (-0-1j)
i to the power of 8 is (1+0j)
i to the power of 9 is 1j
i to the power of 10 is (-1+0j)


We can observe a cyclic behavior as the value of the exponent increases, as follows:

- $i^1=i$
- $i^2=-1$
- $i^3=-i$
- $i^4=1$
- $i^5=i$
- $i^6=-1$
- $i^7=-i$
- $i^8=1$
- $i^9=i$
- $i^{10}=-1$


<a name="task3"></a>
<h3> Task 3</h3>

Consider the vector $b$ and the matrices $B$ and $C$ defined as follows:

$$\vec{b}=\mymatrix{r}{-3i \\ 4+i \\ -3-5i \\ 8-7i} ~~~~~,~~~~~ \mathbf{B} = \mymatrix{rrr}{1 & 2 & -3 \\ -6 & 5 & 4 \\ 9 & 10 & 11 \\ 7 & -8 & 3} ~~~~~,~~~~~ \mathbf{C} = \mymatrix{rrrr}{3.3 & 2.5 & 8.1 & -1.3 \\ 9.2 & -7.5 & 10.6 & 2.8 \\ 4.9 & 6.7 & -12.1 & 0.3} $$

Find:
- $\mathbf{C}\cdot \vec{b}$
- $\mathbf{B}\cdot \mathbf{C}$
- $\mathbf{B}\cdot \vec{b}$

What happens to the dimensions of the result for each case?

What happens with the last case?

<h3>Solution</h3>

In [3]:
# definition of the entities

b = [complex(0, -3), complex(4, 1), complex(-3, -5), complex(8, -7)]

B = [ 
     [ 1 ,  2 , -3], 
     [-6 ,  5 ,  4], 
     [ 9 , 10 , 11],
     [ 7 , -8 ,  3],
    ] 

C = [ 
     [3.3 ,  2.5 ,   8.1 , -1.3], 
     [9.2 , -7.5 ,  10.6 ,  2.8], 
     [4.9 ,  6.7 , -12.1 ,  0.3],
    ] 

In [4]:
# C * b

result_C_b = []

rows_C = len(C)
cols_C = len(C[0])
rows_b = len(b)
for i in range(rows_C):
    result_C_b.append(0)   # start with value '0' to be able to perform the sum
    for j in range(rows_b):
        result_C_b[i] += C[i][j] * b[j]

for i in range(len(result_C_b)):
    print(result_C_b[i])

(-24.699999999999996-38.8j)
(-39.4-107.69999999999999j)
(65.5+50.4j)


In [5]:
# B * C

result_B_C = []

rows_B = len(B)
cols_B = len(B[0])
rows_C = len(C)
cols_C = len(C[0])
for i in range(rows_B):
    result_B_C.append([0] * len(B))   # create a list with zeros of size 'len(B)'
    for j in range(cols_C):
        for k in range(cols_B):
            result_B_C[i][j] += B[i][k] * C[k][j]
                
for i in range(len(result_B_C)):
    print(result_B_C[i])

[6.999999999999998, -32.6, 65.6, 3.4]
[45.800000000000004, -25.7, -43.99999999999999, 23.0]
[175.60000000000002, 21.200000000000003, 45.79999999999998, 19.599999999999998]
[-35.8, 97.6, -64.4, -30.6]


In [6]:
# B * b

# it is not possible to perform this operation

It is not possible to carry out the $\mathbf{B}\cdot \vec{b}$ operation since the dimension of these matrices does not allow it, it is proposed to perform the multiplication of $(4\times 3)\cdot(4\times 1)$ matrices, which does not lead to any possible resulting dimension, more details in _Appendix B_.

Unlike the $\mathbf{C}\cdot \vec{b}$ operation that indicates the multiplication of $(3\times 4)\cdot(4\times 1)$ matrices, which leads us to the result having dimension $(3\times 1)$.

In the case of the $\mathbf{B}\cdot \mathbf{C}$ operation, we have that the multiplication is done with the dimensions $(4\times 3)\cdot(3\times 4)$, which results in a matrix of dimension $(4\times 4)$.

<a name="task4"></a>
<h3> Task 4</h3>

Perform the same cases of _Task 3_, but using the `numpy` package.

If you don't have it installed, do so by running the following command in a new cell:

    !pip install numpy

You can consult the `numpy` documentation [here](https://numpy.org/doc/).

<h3>Solution</h3>

In [7]:
import numpy as np

b = np.array([complex(0, -3), complex(4, 1), complex(-3, -5), complex(8, -7)])

B = np.array([ 
     [ 1 ,  2 , -3], 
     [-6 ,  5 ,  4], 
     [ 9 , 10 , 11],
     [ 7 , -8 ,  3],
    ])

C = np.array([ 
     [3.3 ,  2.5 ,   8.1 , -1.3], 
     [9.2 , -7.5 ,  10.6 ,  2.8], 
     [4.9 ,  6.7 , -12.1 ,  0.3],
    ])

In [8]:
# C * b

res_C_b = C.dot(b)

print(res_C_b)  # enough to print the result, remember that this is a column vector

[-24.7 -38.8j -39.4-107.7j  65.5 +50.4j]


In [9]:
# B * C

res_B_C = B.dot(C)

print(res_B_C)  # print the result

[[  7.  -32.6  65.6   3.4]
 [ 45.8 -25.7 -44.   23. ]
 [175.6  21.2  45.8  19.6]
 [-35.8  97.6 -64.4 -30.6]]


In [10]:
# B * b

# it is not possible to perform this operation

# next line will give an error regarding the dimensions (or shape)
# (uncomment to try it)
# res_B_b = B.dot(b)

<a name="task5"></a>
<h3> Task 5</h3>

Given the vectors $\vec{u}$ and $\vec{v}$:

$$\vec{u}=\mymatrix{r}{3 \\ 4 \\ 0} ~~~~~~,~~~~~~ \vec{v}=\mymatrix{r}{-4 \\ 3 \\ 2}$$


- Write all the code yourself to:
  -  normalize the vector $\vec{u}$
  -  normalize the vector $\vec{v}$
  -  determine if they are orthogonal to each other
- Using the `numpy` package:
  -  normalize the vector $\vec{u}$
  -  normalize the vector $\vec{v}$
  -  determine if they are orthogonal to each other

<h3>Solution</h3>

In [11]:
from math import sqrt

#define the vectors
u = [ 3, 4, 0]
v = [-4, 3, 2]

# calculate u normalized
u_dot_product = 0
for i in range(len(u)):
    u_dot_product += u[i]*u[i]
    
u_norm =sqrt(u_dot_product)

u_normalized = []
for i in range(len(u)):
    u_normalized.append(u[i] / u_norm)

print("vector u normalized:", u_normalized)



# calculate v normalized
v_dot_product = 0
for i in range(len(v)):
    v_dot_product += v[i]*v[i]
    
v_norm =sqrt(v_dot_product)

v_normalized = []
for i in range(len(v)):
    v_normalized.append(v[i] / v_norm)

print("vector v normalized:", v_normalized)



# dot product u.v
dot_product = 0
for i in range(len(u)):
    dot_product += u[i] * v[i]

print("dot product =", dot_product)
if dot_product == 0:
    print("vectors u and v are orthogonal")
else:
    print("vectors u and v are NOT orthogonal")

vector u normalized: [0.6, 0.8, 0.0]
vector v normalized: [-0.7427813527082074, 0.5570860145311556, 0.3713906763541037]
dot product = 0
vectors u and v are orthogonal


In [12]:
import numpy as np

#define the vectors
u = np.array([ 3, 4, 0])
v = np.array([-4, 3, 2])


u_normalized = u / np.linalg.norm(u)
print("vector u normalized:", u_normalized)

v_normalized = v / np.linalg.norm(v)
print("vector v normalized:", v_normalized)


dot_product = u.dot(v)
print("dot product =", dot_product)
if dot_product == 0:
    print("vectors u and v are orthogonal")
else:
    print("vectors u and v are NOT orthogonal")

vector u normalized: [0.6 0.8 0. ]
vector v normalized: [-0.74278135  0.55708601  0.37139068]
dot product = 0
vectors u and v are orthogonal
