# Instructions

The places where you have enter code, to answer the questions, are marked with `# YOUR CODE HERE`. Once you have written your code you should remove any `raise NotImplementedError()` statements.


## Question 1 (3 points)

Complete the function `get_Q` that returns a $Q$ matrix for the following objective function:

$$f(x_1, x_2, x_3, x_4) = 3x_1 + 2x_2 - x_3 - 4 x_4 + 2x_1x_3 - 5x_2x_4
.$$

The function `get_Q` has

- Input: None
- Returns:
    - A `numpy.array` representing the $Q$ matrix


In [21]:
%pip install numpy



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
import numpy as np

def get_Q():
    # YOUR CODE HERE
    Q = np.zeros((4, 4))  # Initialize Q matrix with zeros
    
    # Assign coefficients of quadratic terms
    Q[0, 0] = 0
    Q[1, 1] = 0
    Q[2, 2] = 0
    Q[3, 3] = 0
    Q[0, 2] = Q[2, 0] = 2  # Coefficient of x1*x3 term
    Q[1, 3] = Q[3, 1] = -5  # Coefficient of x2*x4 term

    # raise NotImplementedError()
    # Do not modify anything below this line
    return Q


In [23]:
# You can use this cell to call and check the output of the function

print(get_Q())


[[ 0.  0.  2.  0.]
 [ 0.  0.  0. -5.]
 [ 2.  0.  0.  0.]
 [ 0. -5.  0.  0.]]


In [24]:
# hidden tests will be used for grading.

## Question 2 (5 points)

Complete function `maximize` that takes as input a `Q` matrix and returns the vector that maximizes the objective function.

The function `maximize` has

- Input:
    - A `numpy.array` representing $Q$ matrix
- Returns:
    - A `numpy.array` representing the vector that maximizes the objective function

Hint: You can use the function `qubo_solver` given below. `qubo_solver` takes as input a `Q` matrix and returns the vector of variables that **minimizes** the corresponding function. 


In [39]:
import itertools
import numpy as np


def qubo_solver(Q_matrix):
    possible_values = {}
    # A list of all the possible permutations for x vector
    vec_permutations = itertools.product([0, 1], repeat=Q_matrix.shape[0])

    for permutation in vec_permutations:
        x = np.array(
            [[var] for var in permutation]
        )  # Converts the permutation into a column vector
        value = (x.T).dot(Q_matrix).dot(x)
        possible_values[
            value[0][0]
        ] = x  # Adds the value and its vector to the dictionary

    min_value = min(possible_values.keys())  # Lowest value of the objective function
    opt_vector = tuple(
        possible_values[min_value].T[0]
    )  # Optimum vector x that produces the lowest value

    return opt_vector


In [26]:
def maximize(Q):
    # YOUR CODE HERE

    # Negate the Q matrix to convert minimization to maximization
    negated_Q = -Q.copy()

    # Use the qubo_solver function to find the minimizing vector for the negated matrix
    v = qubo_solver(negated_Q)

    # raise NotImplementedError()
    # Do not modify anything below this line
    return v


In [27]:
# You can use this cell to call and check the output of the function

Q = np.array([[1, 1], [0, -1]])

print(maximize(Q))

(1, 1)


In [28]:
# hidden tests will be used for grading.

In [29]:
# hidden tests will be used for grading.

In [30]:
# hidden tests will be used for grading.

## Question 3 (5 points)

Next questions are about the Knapsack Problem.

Given $n$ items, each with an associated weight $w_i$ and cost $c_i$, the goal of the Knapsack problem is to pack as many items to maximize the value of the packed knapsack, while not exceeding the knapsack capacity $W$.

Let $x_i$ be a binary variable that is equal to 1 if $i$'th item is selected and 0 otherwise. 

Complete the function `objective` so that it returns a string corresponding to the objective function

$$
\max~~f(x_0,x_1,\dots,x_{n-1})
$$
for the Knapsack Problem.

The function `objective` has

- Inputs:
    - `n`: an `int` representing the number of items,
    - `costs`: a list of $n$ elements corresponding to costs of the items,
    - `weights`: a list of $n$ elements corresponding to the weights of the items,
    - `W`: capacity of Knapsack
            
- Returns:
    - A string representation of the objective function

**String representation:** Ex: For $f(x_0,x_1)= 2x_0-3x_0x_1+x_1$, string representation is `2x_0-3x_0x_1+1x_1`. The order of the terms is not important i.e. `-3x_0x_1+1x_1+2x_0` is valid as well.


In [31]:
def objective(n, weights, costs, W):
    # YOUR CODE HERE

    # Initialize an empty string to build the objective function
    objective_str = ""

    # Iterate through each item
    for i in range(n):
        # Add the cost term for each item with its corresponding binary variable
        objective_str += f"{costs[i]}x_{i} + "

    # Add the constraint term for the knapsack capacity
    objective_str += f"-{W}x_{n}"

    # Remove the trailing "+" symbol
    s = objective_str.replace(" + -", " - ")

    # raise NotImplementedError()
    # Do not modify anything below this line
    return s


In [32]:
# You can use this cell to call and check the output of the function
n = 5
W = 10
weights = [1, 4, 8, 2, 3]
costs = [2, 7, 3, 4, 6]
print(objective(n, weights, costs, W))


2x_0 + 7x_1 + 3x_2 + 4x_3 + 6x_4 - 10x_5


In [33]:
# hidden tests will be used for grading.

In [34]:
# hidden tests will be used for grading.
# If this cell results in an error, your implementation is incorrect

## Question 4 (5 points)

Complete the function `constraint` so that it returns a string corresponding to the constraint for the Knapsack Problem.

The function `constraint` has

- Inputs:
    - `n`: an `int`, the number of items,
    - `costs`: a list of $n$ elements corresponding to costs of the items,
    - `weights`- a list of $n$ elements corresponding to the weights of the items,
    - `W`-capacity of Knapsack
            
- Returns:
    - A string representation of the constraint

**String representation:** Ex: For constraint $1x_0+2x_2\leq9$, string representation is `1x_0+2x_2<=9`. The order of the terms is not important i.e. `2x_2+1x_0<=9` is valid as well.


In [35]:
def constraint(n, weights, costs, W):
    # YOUR CODE HERE

    # Initialize an empty string to build the constraint
    constraint_str = ""

    # Iterate through each item
    for i in range(n):
        # Add the weight term for each item with its corresponding binary variable
        constraint_str += f"{weights[i]}x_{i} + "

    # Remove the trailing "+" symbol and add "<=" for the constraint
    s = constraint_str[:-3] + f" <= {W}"

    # raise NotImplementedError()
    # Do not modify anything below this line
    return s


In [36]:
# You can use this cell to call and check the output of the function
n = 5
W = 10
weights = [1, 4, 8, 2, 3]
costs = [2, 7, 3, 4, 6]
print(constraint(n, weights, costs, W))


1x_0 + 4x_1 + 8x_2 + 2x_3 + 3x_4 <= 10


In [37]:
# hidden tests will be used for grading.

In [38]:
# hidden tests will be used for grading.